# This workflow will test a Java project with Maven
# See https://github.com/jonashackt/github-actions-release-maven

name: CI
on: [ pull_request, push, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build & Publish to Maven Central
        run: mvn -U -B validate
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
